const linkGroups = {
  technologiesToProjects: [
    { source: "api", target: "socialmerge" },
    { source: "d3js", target: "socialmerge" },
    { source: "sass", target: "socialmerge" },
    { source: "materialui", target: "socialmerge" },
    { source: "reactjs", target: "socialmerge" },
    { source: "api", target: "spotifyrooms" },
    { source: "tailwindcss", target: "spotifyrooms" },
    { source: "bootstrap", target: "spotifyrooms" },
    { source: "reactjs", target: "spotifyrooms" },
    { source: "api", target: "stocktools" },
    { source: "pandas", target: "stocktools" },
    { source: "django", target: "stocktools" },
    { source: "api", target: "youtubeautomation" },
    { source: "selenium", target: "youtubeautomation" },
    { source: "opencv", target: "youtubeautomation" },
    { source: "ffmpeg", target: "youtubeautomation" },
    { source: "moviepy", target: "youtubeautomation" },
    { source: "threejs", target: "youtubeautomation" },
    { source: "nltk", target: "financialsentiment" },
    { source: "selenium", target: "financialsentiment" },
    { source: "api", target: "financialsentiment" },
    { source: "mongodb", target: "form4analysis" },
    { source: "mongodb", target: "youtubeautomation" },
    { source: "api", target: "form4analysis" },
    { source: "pandas", target: "financialsentiment" },
  ],
  languagesToProjects: [
    { source: "javascript", target: "algovisualizer" },
    { source: "css", target: "algovisualizer" },
    { source: "html", target: "algovisualizer" },
    { source: "javascript", target: "socialmerge" },
    { source: "css", target: "socialmerge" },
    { source: "html", target: "socialmerge" },
    { source: "javascript", target: "spotifyrooms" },
    { source: "css", target: "spotifyrooms" },
    { source: "html", target: "spotifyrooms" },
    { source: "python", target: "stocktools" },
    { source: "css", target: "stocktools" },
    { source: "html", target: "stocktools" },
    { source: "python", target: "youtubeautomation" },
    { source: "python", target: "financialsentiment" },
    { source: "python", target: "form4analysis" },
  ],
  // languagesToTechnologies: [
  //   { source: "Javascript", target: "Bootstrap" },
  //   { source: "Javascript", target: "D3.js" },
  //   { source: "Javascript", target: "MaterialUI" },
  //   { source: "Javascript", target: "React.js" },
  //   { source: "Javascript", target: "Three.js" },
  //   { source: "CSS", target: "Sass" },
  //   { source: "CSS", target: "Tailwind CSS" },
  //   { source: "Python", target: "MoviePy" },
  //   { source: "Python", target: "OpenCV" },
  //   { source: "Python", target: "Pandas" },
  //   { source: "Python", target: "Selenium" },
  //   // { source: "Python", target: "FFmpeg" },
  // ],
};

export default linkGroups;
